#!/usr/bin/env python3
import os
import subprocess
import argparse
import logging
from pprint import pprint

import utils.conf as conf

bsflDescription = '''Big Stupid For Loop'''

# Setup argparse
parser = argparse.ArgumentParser(description=bsflDescription)
parser.add_argument('configFile', metavar='/path/to/job.yaml', type=argparse.FileType('r'), help="Path to job yaml file")
parser.add_argument("-v", "--verbose", help="increase output verbosity", action="store_true")
args = parser.parse_args()

# Setup logging
# TODO: setup log formater
if args.verbose:
    logging.basicConfig(level=logging.DEBUG)

if __name__ == '__main__':
    # Load workingConfig
    workingConfig = conf.parse(args.configFile)
    # Lint workingConfig
    conf.lint(workingConfig)
    # pprint(workingConfig)

    # Build Inventory
    workingInv = workingConfig['inventory']
