#!/usr/bin/env python3 -u
"""
Testing step plugin for bsfl. Prints 'Beep.' 10 times once per second by default.
"""
from argparse import ArgumentParser
from time import sleep, time


if __name__ == '__main__':
    # Setup argparse
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('message', default='Beep.', type=str, nargs='*', help='log message to print')
    parser.add_argument('-w', '--wait', default=1.0, type=float, help='Wait between log lines')
    parser.add_argument('-c', '--count', default=10, type=int, help='Number of log lines to print')
    args = parser.parse_args()

    for _ in range(args.count):
        print('%s - %s' % (int(time()), ' '.join(args.message)))
        sleep(args.wait)
    exit(0)
